### ISSUE TITLE
Change in behavior between 1.8.3 and 1.8.4 Python 2.7.10

### ISSUE THREAD

**Issue by papachoco** [hamcrest/PyHamcrest#56]
The following statements work fine in 1.8.3
from hamcrest import is_
from hamcrest import assert_that
result = ()
assert_that(result, is_(()))

However in 1.8.4. I get

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.10-x86_64/egg/hamcrest/core/assert_that.py", line 43, in assert_that
  File "build/bdist.macosx-10.10-x86_64/egg/hamcrest/core/assert_that.py", line 57, in _assert_match
AssertionError: 
Expected: an instance of one of 
     but: was <()>

Thanks a lot

Carlos

**Comment by offbyone** [comment]
Huh. That is odd. I'll see what I can make work there. 



—
Chris
offbyone on GitHub, offby1 on twitter

**Comment by offbyone** [comment]
Fixed in 1.8.5

**Comment by papachoco** [comment]
Thanks a lot
