### ISSUE TITLE
nested dict match with hasentry and hasentries cannot handle partial match use case

### ISSUE THREAD

**Issue by JPvRiel** [hamcrest/PyHamcrest#76]
This was more or less raised before, but closed due to the way the issue was interpreted: https://github.com/hamcrest/PyHamcrest/issues/37

The question remains, how should one find matches within dictionaries with nested structures? Especially only partial matches? This is a common case when dealing with JSON and using python's standards json lib to map json into dict objects.

E.g. run this

```python
import json
from hamcrest import *

json_obj = """
  {
    "flat": "easy to match",
    "nested": {
      "n1": "find me",
      "n2": "ignore me"
    }
  }
  """
json_find_all = """
  {
    "nested": {
      "n1": "find me",
      "n2": "ignore me"
    }
  }
  """
json_find_some = """
  {
    "nested": {
      "n1": "find me"
    }
  }
  """
dict_obj = json.loads(json_obj)
dict_find_all = json.loads(json_find_all)
dict_find_some = json.loads(json_find_some)
assert_that(dict_obj, has_entries(dict_find_all))
print("can find full nested match")
assert_that(dict_obj, has_entries(dict_find_some))
print("can't find partial nested match")
```

And note the output

```
can find full nested match
Traceback (most recent call last):
  File "hamcrest_nested_dict.py", line 33, in <module>
    assert_that(dict_obj, has_entries(dict_find_some))
  File "/home/a211278l/.local/lib/python3.5/site-packages/hamcrest/core/assert_that.py", line 43, in assert_that
    _assert_match(actual=arg1, matcher=arg2, reason=arg3)
  File "/home/a211278l/.local/lib/python3.5/site-packages/hamcrest/core/assert_that.py", line 57, in _assert_match
    raise AssertionError(description)
AssertionError: 
Expected: a dictionary containing {'nested': <{'n1': 'find me'}>}
     but: value for 'nested' was <{'n2': 'ignore me', 'n1': 'find me'}>
```

**Comment by JPvRiel** [comment]
https://stackoverflow.com/a/30818799 has a workable answer.

I had to do the following workaround, which isn't ideal, given it doesn't show the dict objects in assertion output:

```python
# hamcrest cannot handle nested dict objects
#assert_that(dict_obj, has_entries(dict_find))
json_sub_match = dict_find.items() <= dict_obj.items()
assert_that(json_sub_match, equal_to(True))
```

**Comment by YuppY** [comment]
You have to nest `has_entries`:
```python
assert_that(
  {
    "flat": "easy to match",
    "nested": {
      "n1": "find me",
      "n2": "ignore me"
    }
  }, 
  has_entries({"nested": has_entries({"n1": "find me"})})
)
```

**Comment by offbyone** [comment]
@YuppY seems to have the right answer; does that sort this out?

**Comment by brunns** [comment]
Agreed - this can be closed.

**Comment by brunns** [comment]
Closing, since there's been no more feedback on this.
